spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create